project:
  type: book
  output-dir: docs

book:
  title: "Capstone"
  downloads: [pdf]
  author: "Team"
  date: today
  chapters:
    - index.qmd
    - github.qmd
    
  site-url: https://adyadyan.github.io/MAP-5629-Capstone/
  repo-url: https://github.com/adyadyan/MAP-5629-Capstone
  repo-actions: [edit, source, issue]
  search: true
    
format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    toc-depth: 2